name: Weather App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask requests

      - name: Run the backend server
        run: |
          python backend/server.py & 
          sleep 5  # Attendre que le serveur soit lancé

      - name: Test server
        run: |
          curl -s http://127.0.0.1:5000/ > /dev/null
          curl -s -X POST -d "city=Paris" http://127.0.0.1:5000/weather > result.html
